### ISSUE TITLE
unable to retrieve task due to sg api error

### ISSUE THREAD

**Issue by Byron** [Byron/bshotgun#1]
When retrieving the entire database, it seems there was an error converting an unexpected value:

``` python
Traceback (most recent call last):
  File "[...]/bdevel/lib/components/core/src/python/bcmd/base.py", line 322, in parse_and_execute
    return self.execute(parsed_args, remaining_args)
  File "[...]/bdevel/lib/components/core/src/python/bcmd/base.py", line 196, in execute
    return cmd.execute(args, remaining_args)
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/plugins/be_shotgun.py", line 114, in execute
    SQLProxyShotgunConnection.init_database(getattr(args, 'sqlalchemy-url'), tf, fetcher)
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/sql.py", line 162, in init_database
    for rid, record in enumerate(fetch_entity_data_fun(type_name)):
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/plugins/be_shotgun.py", line 113, in <lambda>
    fetcher = lambda tn: conn.find(tn, list(), tf.schema_by_name(tn).keys())
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/base.py", line 64, in func
    return getattr(getattr(instance, proxy_attr), method_name)(*args, **kwargs)
  File "[...]/bdep-nonfree/lib/shotgun-python-api/latest/noarch/shotgun_api3/shotgun.py", line 537, in find
    result = self._call_rpc("read", params)
  File "[...]/bdep-nonfree/lib/shotgun-python-api/latest/noarch/shotgun_api3/shotgun.py", line 1512, in _call_rpc
    self._response_errors(response)
  File "[...]/bdep-nonfree/lib/shotgun-python-api/latest/noarch/shotgun_api3/shotgun.py", line 1719, in _response_errors
    "Unknown Error"))
Fault: API read() CRUD ERROR #10: Read failed for entity type [Task]: can't convert nil into String
```

**Comment by Byron** [comment]
It seems the error is happening on their side, i.e. Ruby, and thus can't be prevented.
Will have to identify the entity and fix it.

**Comment by Byron** [comment]
For completeness, the code doing this is `sg.find('Task', [], task_schema)`, where `task_schema` is a list of all attributes according to the schema retrieved via shotgun API. I suspect that using the entire set of allowed attributes triggers the problem.

**Comment by Byron** [comment]
Dropped e-mail to shotgun support, while trying to find the broken instance using brute force over night.

**Comment by Byron** [comment]
After querying 12k tasks, there was still none with an error. As there are no 12k tasks in the database, I assume that `sg.find_one('Task', [], task_schema)` is not the same as `sg.find('Task', [], task_schema)`, as the latter one crashes, the first one does not.
SG Support is on it, after all `can't convert nil to string` is coming from ruby.

**Comment by Byron** [comment]
Support suggested to not fetch the `sibling_tasks` field, that seems to contain the `nil` value. I would have been happy if they could just have removed the offending value. 

Trying to pull all data again, without that field:

``` python
ERROR:be:An unhandled exception occurred
Traceback (most recent call last):
  File "[...]/bdevel/lib/components/core/src/python/bcmd/base.py", line 322, in parse_and_execute
    return self.execute(parsed_args, remaining_args)
  File "[...]/bdevel/lib/components/core/src/python/bcmd/base.py", line 196, in execute
    return cmd.execute(args, remaining_args)
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/tests/plugins/be_shotgun_tests.py", line 295, in execute
    ShotgunTestDatabase(sample_name=getattr(args, 'db-name')).rebuild_database(args.type_names, args.fetcher)
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/tests/base.py", line 147, in rebuild_database
    records = fetcher(type_name)
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/tests/plugins/be_shotgun_tests.py", line 188, in <lambda>
    args.fetcher = lambda tn: scrambler(conn.find(tn, list(), fac.schema_by_name(tn).keys()), fac.type_names())
  File "[...]/bdevel/lib/integrations/shotgun/src/python/bshotgun/base.py", line 64, in func
    return getattr(getattr(instance, proxy_attr), method_name)(*args, **kwargs)
  File "[...]/bdep-nonfree/lib/shotgun-python-api/latest/noarch/shotgun_api3/shotgun.py", line 526, in find
    result = self._call_rpc("read", params)
  File "[...]/bdep-nonfree/lib/shotgun-python-api/latest/noarch/shotgun_api3/shotgun.py", line 1503, in _call_rpc
    self._parse_http_status(http_status)
  File "[...]/bdep-nonfree/lib/shotgun-python-api/latest/noarch/shotgun_api3/shotgun.py", line 1657, in _parse_http_status
    headers)
ProtocolError: <ProtocolError for XXX.shotgunstudio.com: 503 Shotgun is currently down for maintenance. Please try again later.>
```

Will try again

**Comment by Byron** [comment]
It worked now, will ask support to fix this issue for good.

**Comment by Byron** [comment]
- [x] ask support
- [x] workaround issue
- [x] close this issue as there might not be any more feedback from them anyway
